// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/cqrs/base"
	"github.com/bborbe/time"
	"github.com/bborbe/notification/cmd/frontend/pkg/index"
	"github.com/bborbe/notification"
)

type NotificationIndexSearcher struct {
	SearchStub        func(context.Context, *time.DateTime, *time.DateTime, core.NotificationTypes, []core.NotificationTarget, []string, []string, []string, string, int) (base.Identifiers, error)
	searchMutex       sync.RWMutex
	searchArgsForCall []struct {
		arg1  context.Context
		arg2  *time.DateTime
		arg3  *time.DateTime
		arg4  core.NotificationTypes
		arg5  []core.NotificationTarget
		arg6  []string
		arg7  []string
		arg8  []string
		arg9  string
		arg10 int
	}
	searchReturns struct {
		result1 base.Identifiers
		result2 error
	}
	searchReturnsOnCall map[int]struct {
		result1 base.Identifiers
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NotificationIndexSearcher) Search(arg1 context.Context, arg2 *time.DateTime, arg3 *time.DateTime, arg4 core.NotificationTypes, arg5 []core.NotificationTarget, arg6 []string, arg7 []string, arg8 []string, arg9 string, arg10 int) (base.Identifiers, error) {
	var arg5Copy []core.NotificationTarget
	if arg5 != nil {
		arg5Copy = make([]core.NotificationTarget, len(arg5))
		copy(arg5Copy, arg5)
	}
	fake.searchMutex.Lock()
	ret, specificReturn := fake.searchReturnsOnCall[len(fake.searchArgsForCall)]
	fake.searchArgsForCall = append(fake.searchArgsForCall, struct {
		arg1  context.Context
		arg2  *time.DateTime
		arg3  *time.DateTime
		arg4  core.NotificationTypes
		arg5  []core.NotificationTarget
		arg6  []string
		arg7  []string
		arg8  []string
		arg9  string
		arg10 int
	}{arg1, arg2, arg3, arg4, arg5Copy, arg6, arg7, arg8, arg9, arg10})
	stub := fake.SearchStub
	fakeReturns := fake.searchReturns
	fake.recordInvocation("Search", []interface{}{arg1, arg2, arg3, arg4, arg5Copy, arg6, arg7, arg8, arg9, arg10})
	fake.searchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *NotificationIndexSearcher) SearchCallCount() int {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	return len(fake.searchArgsForCall)
}

func (fake *NotificationIndexSearcher) SearchCalls(stub func(context.Context, *time.DateTime, *time.DateTime, core.NotificationTypes, []core.NotificationTarget, []string, []string, []string, string, int) (base.Identifiers, error)) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = stub
}

func (fake *NotificationIndexSearcher) SearchArgsForCall(i int) (context.Context, *time.DateTime, *time.DateTime, core.NotificationTypes, []core.NotificationTarget, []string, []string, []string, string, int) {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	argsForCall := fake.searchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7, argsForCall.arg8, argsForCall.arg9, argsForCall.arg10
}

func (fake *NotificationIndexSearcher) SearchReturns(result1 base.Identifiers, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	fake.searchReturns = struct {
		result1 base.Identifiers
		result2 error
	}{result1, result2}
}

func (fake *NotificationIndexSearcher) SearchReturnsOnCall(i int, result1 base.Identifiers, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	if fake.searchReturnsOnCall == nil {
		fake.searchReturnsOnCall = make(map[int]struct {
			result1 base.Identifiers
			result2 error
		})
	}
	fake.searchReturnsOnCall[i] = struct {
		result1 base.Identifiers
		result2 error
	}{result1, result2}
}

func (fake *NotificationIndexSearcher) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *NotificationIndexSearcher) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ index.NotificationIndexSearcher = new(NotificationIndexSearcher)
