// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/notification/command/discord"
)

type CommandSendCommandObjectSender struct {
	SendCommandStub        func(context.Context, discord.SendCommand) error
	sendCommandMutex       sync.RWMutex
	sendCommandArgsForCall []struct {
		arg1 context.Context
		arg2 discord.SendCommand
	}
	sendCommandReturns struct {
		result1 error
	}
	sendCommandReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CommandSendCommandObjectSender) SendCommand(arg1 context.Context, arg2 discord.SendCommand) error {
	fake.sendCommandMutex.Lock()
	ret, specificReturn := fake.sendCommandReturnsOnCall[len(fake.sendCommandArgsForCall)]
	fake.sendCommandArgsForCall = append(fake.sendCommandArgsForCall, struct {
		arg1 context.Context
		arg2 discord.SendCommand
	}{arg1, arg2})
	stub := fake.SendCommandStub
	fakeReturns := fake.sendCommandReturns
	fake.recordInvocation("SendCommand", []interface{}{arg1, arg2})
	fake.sendCommandMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CommandSendCommandObjectSender) SendCommandCallCount() int {
	fake.sendCommandMutex.RLock()
	defer fake.sendCommandMutex.RUnlock()
	return len(fake.sendCommandArgsForCall)
}

func (fake *CommandSendCommandObjectSender) SendCommandCalls(stub func(context.Context, discord.SendCommand) error) {
	fake.sendCommandMutex.Lock()
	defer fake.sendCommandMutex.Unlock()
	fake.SendCommandStub = stub
}

func (fake *CommandSendCommandObjectSender) SendCommandArgsForCall(i int) (context.Context, discord.SendCommand) {
	fake.sendCommandMutex.RLock()
	defer fake.sendCommandMutex.RUnlock()
	argsForCall := fake.sendCommandArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *CommandSendCommandObjectSender) SendCommandReturns(result1 error) {
	fake.sendCommandMutex.Lock()
	defer fake.sendCommandMutex.Unlock()
	fake.SendCommandStub = nil
	fake.sendCommandReturns = struct {
		result1 error
	}{result1}
}

func (fake *CommandSendCommandObjectSender) SendCommandReturnsOnCall(i int, result1 error) {
	fake.sendCommandMutex.Lock()
	defer fake.sendCommandMutex.Unlock()
	fake.SendCommandStub = nil
	if fake.sendCommandReturnsOnCall == nil {
		fake.sendCommandReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.sendCommandReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CommandSendCommandObjectSender) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CommandSendCommandObjectSender) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ discord.SendCommandObjectSender = new(CommandSendCommandObjectSender)
