// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/cqrs/base"
	"github.com/bborbe/kv"
	"github.com/bborbe/notification"
)

type CoreNotificationStoreTx struct {
	AddStub        func(context.Context, kv.Tx, core.Notification) error
	addMutex       sync.RWMutex
	addArgsForCall []struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 core.Notification
	}
	addReturns struct {
		result1 error
	}
	addReturnsOnCall map[int]struct {
		result1 error
	}
	FindStub        func(context.Context, kv.Tx, func(notification core.Notification) bool, chan<- core.Notification) error
	findMutex       sync.RWMutex
	findArgsForCall []struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 func(notification core.Notification) bool
		arg4 chan<- core.Notification
	}
	findReturns struct {
		result1 error
	}
	findReturnsOnCall map[int]struct {
		result1 error
	}
	GetStub        func(context.Context, kv.Tx, base.Identifier) (*core.Notification, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 base.Identifier
	}
	getReturns struct {
		result1 *core.Notification
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 *core.Notification
		result2 error
	}
	MapStub        func(context.Context, kv.Tx, func(ctx context.Context, notification core.Notification) error) error
	mapMutex       sync.RWMutex
	mapArgsForCall []struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 func(ctx context.Context, notification core.Notification) error
	}
	mapReturns struct {
		result1 error
	}
	mapReturnsOnCall map[int]struct {
		result1 error
	}
	RemoveStub        func(context.Context, kv.Tx, base.Identifier) error
	removeMutex       sync.RWMutex
	removeArgsForCall []struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 base.Identifier
	}
	removeReturns struct {
		result1 error
	}
	removeReturnsOnCall map[int]struct {
		result1 error
	}
	StreamStub        func(context.Context, kv.Tx, chan<- core.Notification) error
	streamMutex       sync.RWMutex
	streamArgsForCall []struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 chan<- core.Notification
	}
	streamReturns struct {
		result1 error
	}
	streamReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *CoreNotificationStoreTx) Add(arg1 context.Context, arg2 kv.Tx, arg3 core.Notification) error {
	fake.addMutex.Lock()
	ret, specificReturn := fake.addReturnsOnCall[len(fake.addArgsForCall)]
	fake.addArgsForCall = append(fake.addArgsForCall, struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 core.Notification
	}{arg1, arg2, arg3})
	stub := fake.AddStub
	fakeReturns := fake.addReturns
	fake.recordInvocation("Add", []interface{}{arg1, arg2, arg3})
	fake.addMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CoreNotificationStoreTx) AddCallCount() int {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	return len(fake.addArgsForCall)
}

func (fake *CoreNotificationStoreTx) AddCalls(stub func(context.Context, kv.Tx, core.Notification) error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = stub
}

func (fake *CoreNotificationStoreTx) AddArgsForCall(i int) (context.Context, kv.Tx, core.Notification) {
	fake.addMutex.RLock()
	defer fake.addMutex.RUnlock()
	argsForCall := fake.addArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CoreNotificationStoreTx) AddReturns(result1 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	fake.addReturns = struct {
		result1 error
	}{result1}
}

func (fake *CoreNotificationStoreTx) AddReturnsOnCall(i int, result1 error) {
	fake.addMutex.Lock()
	defer fake.addMutex.Unlock()
	fake.AddStub = nil
	if fake.addReturnsOnCall == nil {
		fake.addReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.addReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CoreNotificationStoreTx) Find(arg1 context.Context, arg2 kv.Tx, arg3 func(notification core.Notification) bool, arg4 chan<- core.Notification) error {
	fake.findMutex.Lock()
	ret, specificReturn := fake.findReturnsOnCall[len(fake.findArgsForCall)]
	fake.findArgsForCall = append(fake.findArgsForCall, struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 func(notification core.Notification) bool
		arg4 chan<- core.Notification
	}{arg1, arg2, arg3, arg4})
	stub := fake.FindStub
	fakeReturns := fake.findReturns
	fake.recordInvocation("Find", []interface{}{arg1, arg2, arg3, arg4})
	fake.findMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CoreNotificationStoreTx) FindCallCount() int {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	return len(fake.findArgsForCall)
}

func (fake *CoreNotificationStoreTx) FindCalls(stub func(context.Context, kv.Tx, func(notification core.Notification) bool, chan<- core.Notification) error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = stub
}

func (fake *CoreNotificationStoreTx) FindArgsForCall(i int) (context.Context, kv.Tx, func(notification core.Notification) bool, chan<- core.Notification) {
	fake.findMutex.RLock()
	defer fake.findMutex.RUnlock()
	argsForCall := fake.findArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *CoreNotificationStoreTx) FindReturns(result1 error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	fake.findReturns = struct {
		result1 error
	}{result1}
}

func (fake *CoreNotificationStoreTx) FindReturnsOnCall(i int, result1 error) {
	fake.findMutex.Lock()
	defer fake.findMutex.Unlock()
	fake.FindStub = nil
	if fake.findReturnsOnCall == nil {
		fake.findReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.findReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CoreNotificationStoreTx) Get(arg1 context.Context, arg2 kv.Tx, arg3 base.Identifier) (*core.Notification, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 base.Identifier
	}{arg1, arg2, arg3})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2, arg3})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *CoreNotificationStoreTx) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *CoreNotificationStoreTx) GetCalls(stub func(context.Context, kv.Tx, base.Identifier) (*core.Notification, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *CoreNotificationStoreTx) GetArgsForCall(i int) (context.Context, kv.Tx, base.Identifier) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CoreNotificationStoreTx) GetReturns(result1 *core.Notification, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *core.Notification
		result2 error
	}{result1, result2}
}

func (fake *CoreNotificationStoreTx) GetReturnsOnCall(i int, result1 *core.Notification, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *core.Notification
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *core.Notification
		result2 error
	}{result1, result2}
}

func (fake *CoreNotificationStoreTx) Map(arg1 context.Context, arg2 kv.Tx, arg3 func(ctx context.Context, notification core.Notification) error) error {
	fake.mapMutex.Lock()
	ret, specificReturn := fake.mapReturnsOnCall[len(fake.mapArgsForCall)]
	fake.mapArgsForCall = append(fake.mapArgsForCall, struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 func(ctx context.Context, notification core.Notification) error
	}{arg1, arg2, arg3})
	stub := fake.MapStub
	fakeReturns := fake.mapReturns
	fake.recordInvocation("Map", []interface{}{arg1, arg2, arg3})
	fake.mapMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CoreNotificationStoreTx) MapCallCount() int {
	fake.mapMutex.RLock()
	defer fake.mapMutex.RUnlock()
	return len(fake.mapArgsForCall)
}

func (fake *CoreNotificationStoreTx) MapCalls(stub func(context.Context, kv.Tx, func(ctx context.Context, notification core.Notification) error) error) {
	fake.mapMutex.Lock()
	defer fake.mapMutex.Unlock()
	fake.MapStub = stub
}

func (fake *CoreNotificationStoreTx) MapArgsForCall(i int) (context.Context, kv.Tx, func(ctx context.Context, notification core.Notification) error) {
	fake.mapMutex.RLock()
	defer fake.mapMutex.RUnlock()
	argsForCall := fake.mapArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CoreNotificationStoreTx) MapReturns(result1 error) {
	fake.mapMutex.Lock()
	defer fake.mapMutex.Unlock()
	fake.MapStub = nil
	fake.mapReturns = struct {
		result1 error
	}{result1}
}

func (fake *CoreNotificationStoreTx) MapReturnsOnCall(i int, result1 error) {
	fake.mapMutex.Lock()
	defer fake.mapMutex.Unlock()
	fake.MapStub = nil
	if fake.mapReturnsOnCall == nil {
		fake.mapReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.mapReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CoreNotificationStoreTx) Remove(arg1 context.Context, arg2 kv.Tx, arg3 base.Identifier) error {
	fake.removeMutex.Lock()
	ret, specificReturn := fake.removeReturnsOnCall[len(fake.removeArgsForCall)]
	fake.removeArgsForCall = append(fake.removeArgsForCall, struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 base.Identifier
	}{arg1, arg2, arg3})
	stub := fake.RemoveStub
	fakeReturns := fake.removeReturns
	fake.recordInvocation("Remove", []interface{}{arg1, arg2, arg3})
	fake.removeMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CoreNotificationStoreTx) RemoveCallCount() int {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	return len(fake.removeArgsForCall)
}

func (fake *CoreNotificationStoreTx) RemoveCalls(stub func(context.Context, kv.Tx, base.Identifier) error) {
	fake.removeMutex.Lock()
	defer fake.removeMutex.Unlock()
	fake.RemoveStub = stub
}

func (fake *CoreNotificationStoreTx) RemoveArgsForCall(i int) (context.Context, kv.Tx, base.Identifier) {
	fake.removeMutex.RLock()
	defer fake.removeMutex.RUnlock()
	argsForCall := fake.removeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CoreNotificationStoreTx) RemoveReturns(result1 error) {
	fake.removeMutex.Lock()
	defer fake.removeMutex.Unlock()
	fake.RemoveStub = nil
	fake.removeReturns = struct {
		result1 error
	}{result1}
}

func (fake *CoreNotificationStoreTx) RemoveReturnsOnCall(i int, result1 error) {
	fake.removeMutex.Lock()
	defer fake.removeMutex.Unlock()
	fake.RemoveStub = nil
	if fake.removeReturnsOnCall == nil {
		fake.removeReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.removeReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CoreNotificationStoreTx) Stream(arg1 context.Context, arg2 kv.Tx, arg3 chan<- core.Notification) error {
	fake.streamMutex.Lock()
	ret, specificReturn := fake.streamReturnsOnCall[len(fake.streamArgsForCall)]
	fake.streamArgsForCall = append(fake.streamArgsForCall, struct {
		arg1 context.Context
		arg2 kv.Tx
		arg3 chan<- core.Notification
	}{arg1, arg2, arg3})
	stub := fake.StreamStub
	fakeReturns := fake.streamReturns
	fake.recordInvocation("Stream", []interface{}{arg1, arg2, arg3})
	fake.streamMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *CoreNotificationStoreTx) StreamCallCount() int {
	fake.streamMutex.RLock()
	defer fake.streamMutex.RUnlock()
	return len(fake.streamArgsForCall)
}

func (fake *CoreNotificationStoreTx) StreamCalls(stub func(context.Context, kv.Tx, chan<- core.Notification) error) {
	fake.streamMutex.Lock()
	defer fake.streamMutex.Unlock()
	fake.StreamStub = stub
}

func (fake *CoreNotificationStoreTx) StreamArgsForCall(i int) (context.Context, kv.Tx, chan<- core.Notification) {
	fake.streamMutex.RLock()
	defer fake.streamMutex.RUnlock()
	argsForCall := fake.streamArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *CoreNotificationStoreTx) StreamReturns(result1 error) {
	fake.streamMutex.Lock()
	defer fake.streamMutex.Unlock()
	fake.StreamStub = nil
	fake.streamReturns = struct {
		result1 error
	}{result1}
}

func (fake *CoreNotificationStoreTx) StreamReturnsOnCall(i int, result1 error) {
	fake.streamMutex.Lock()
	defer fake.streamMutex.Unlock()
	fake.StreamStub = nil
	if fake.streamReturnsOnCall == nil {
		fake.streamReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.streamReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *CoreNotificationStoreTx) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *CoreNotificationStoreTx) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ core.NotificationStoreTx = new(CoreNotificationStoreTx)
